// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/recognize": {
    params: {};
  };
  "/social": {
    params: {};
  };
  "/social/my-posts": {
    params: {};
  };
  "/social/recommended": {
    params: {};
  };
  "/social/notifications": {
    params: {};
  };
  "/social/following": {
    params: {};
  };
  "/social/followers": {
    params: {};
  };
  "/social/trends": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/profile" | "/recognize" | "/social" | "/social/my-posts" | "/social/recommended" | "/social/notifications" | "/social/following" | "/social/followers" | "/social/trends";
  };
  "./layout/rootLayout.tsx": {
    id: "layout/rootLayout";
    page: "/" | "/login" | "/register" | "/profile" | "/recognize" | "/social" | "/social/my-posts" | "/social/recommended" | "/social/notifications" | "/social/following" | "/social/followers" | "/social/trends";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/LoginPage.tsx": {
    id: "pages/LoginPage";
    page: "/login";
  };
  "./pages/RegisterPage.tsx": {
    id: "pages/RegisterPage";
    page: "/register";
  };
  "./pages/ProfilePage.tsx": {
    id: "pages/ProfilePage";
    page: "/profile";
  };
  "./pages/Recognize.tsx": {
    id: "pages/Recognize";
    page: "/recognize";
  };
  "./layout/socialLayout.tsx": {
    id: "layout/socialLayout";
    page: "/social" | "/social/my-posts" | "/social/recommended" | "/social/notifications" | "/social/following" | "/social/followers" | "/social/trends";
  };
  "./pages/social/HomePage.tsx": {
    id: "pages/social/HomePage";
    page: "/social";
  };
  "./pages/social/MyPostsPage.tsx": {
    id: "pages/social/MyPostsPage";
    page: "/social/my-posts";
  };
  "./pages/social/RecommendedPage.tsx": {
    id: "pages/social/RecommendedPage";
    page: "/social/recommended";
  };
  "./pages/social/NotificationsPage.tsx": {
    id: "pages/social/NotificationsPage";
    page: "/social/notifications";
  };
  "./pages/social/FollowingPage.tsx": {
    id: "pages/social/FollowingPage";
    page: "/social/following";
  };
  "./pages/social/FollowersPage.tsx": {
    id: "pages/social/FollowersPage";
    page: "/social/followers";
  };
  "./pages/social/TrendsPage.tsx": {
    id: "pages/social/TrendsPage";
    page: "/social/trends";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layout/rootLayout": typeof import("./src/./layout/rootLayout.tsx");
  "pages/Home": typeof import("./src/./pages/Home.tsx");
  "pages/LoginPage": typeof import("./src/./pages/LoginPage.tsx");
  "pages/RegisterPage": typeof import("./src/./pages/RegisterPage.tsx");
  "pages/ProfilePage": typeof import("./src/./pages/ProfilePage.tsx");
  "pages/Recognize": typeof import("./src/./pages/Recognize.tsx");
  "layout/socialLayout": typeof import("./src/./layout/socialLayout.tsx");
  "pages/social/HomePage": typeof import("./src/./pages/social/HomePage.tsx");
  "pages/social/MyPostsPage": typeof import("./src/./pages/social/MyPostsPage.tsx");
  "pages/social/RecommendedPage": typeof import("./src/./pages/social/RecommendedPage.tsx");
  "pages/social/NotificationsPage": typeof import("./src/./pages/social/NotificationsPage.tsx");
  "pages/social/FollowingPage": typeof import("./src/./pages/social/FollowingPage.tsx");
  "pages/social/FollowersPage": typeof import("./src/./pages/social/FollowersPage.tsx");
  "pages/social/TrendsPage": typeof import("./src/./pages/social/TrendsPage.tsx");
};