// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/password-reset": {
    params: {};
  };
  "/email-verification": {
    params: {};
  };
  "/email-verification-success": {
    params: {};
  };
  "/teach": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/sessions": {
    params: {};
  };
  "/devices": {
    params: {};
  };
  "/vocabulary": {
    params: {};
  };
  "/social": {
    params: {};
  };
  "/social/my-posts": {
    params: {};
  };
  "/social/recommended": {
    params: {};
  };
  "/social/notifications": {
    params: {};
  };
  "/social/following": {
    params: {};
  };
  "/social/followers": {
    params: {};
  };
  "/social/trends": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/password-reset" | "/email-verification" | "/email-verification-success" | "/teach" | "/profile" | "/sessions" | "/devices" | "/vocabulary" | "/social" | "/social/my-posts" | "/social/recommended" | "/social/notifications" | "/social/following" | "/social/followers" | "/social/trends";
  };
  "./layout/authLayout.tsx": {
    id: "layout/authLayout";
    page: "/login" | "/register" | "/password-reset" | "/email-verification" | "/email-verification-success";
  };
  "./pages/LoginPage.tsx": {
    id: "pages/LoginPage";
    page: "/login";
  };
  "./pages/RegisterPage.tsx": {
    id: "pages/RegisterPage";
    page: "/register";
  };
  "./pages/PasswordResetPage.tsx": {
    id: "pages/PasswordResetPage";
    page: "/password-reset";
  };
  "./pages/EmailVerificationPage.tsx": {
    id: "pages/EmailVerificationPage";
    page: "/email-verification";
  };
  "./pages/EmailVerificationSuccessPage.tsx": {
    id: "pages/EmailVerificationSuccessPage";
    page: "/email-verification-success";
  };
  "./layout/rootLayout.tsx": {
    id: "layout/rootLayout";
    page: "/" | "/teach" | "/profile" | "/sessions" | "/devices" | "/vocabulary" | "/social" | "/social/my-posts" | "/social/recommended" | "/social/notifications" | "/social/following" | "/social/followers" | "/social/trends";
  };
  "./pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "./pages/teach/HomePage.tsx": {
    id: "pages/teach/HomePage";
    page: "/teach";
  };
  "./pages/ProfilePage.tsx": {
    id: "pages/ProfilePage";
    page: "/profile";
  };
  "./pages/SessionsPage.tsx": {
    id: "pages/SessionsPage";
    page: "/sessions";
  };
  "./pages/DevicesPage.tsx": {
    id: "pages/DevicesPage";
    page: "/devices";
  };
  "./pages/vocabulary/HomePage.tsx": {
    id: "pages/vocabulary/HomePage";
    page: "/vocabulary";
  };
  "./layout/socialLayout.tsx": {
    id: "layout/socialLayout";
    page: "/social" | "/social/my-posts" | "/social/recommended" | "/social/notifications" | "/social/following" | "/social/followers" | "/social/trends";
  };
  "./pages/social/HomePage.tsx": {
    id: "pages/social/HomePage";
    page: "/social";
  };
  "./pages/social/MyPostsPage.tsx": {
    id: "pages/social/MyPostsPage";
    page: "/social/my-posts";
  };
  "./pages/social/RecommendedPage.tsx": {
    id: "pages/social/RecommendedPage";
    page: "/social/recommended";
  };
  "./pages/social/NotificationsPage.tsx": {
    id: "pages/social/NotificationsPage";
    page: "/social/notifications";
  };
  "./pages/social/FollowingPage.tsx": {
    id: "pages/social/FollowingPage";
    page: "/social/following";
  };
  "./pages/social/FollowersPage.tsx": {
    id: "pages/social/FollowersPage";
    page: "/social/followers";
  };
  "./pages/social/TrendsPage.tsx": {
    id: "pages/social/TrendsPage";
    page: "/social/trends";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "layout/authLayout": typeof import("./src/./layout/authLayout.tsx");
  "pages/LoginPage": typeof import("./src/./pages/LoginPage.tsx");
  "pages/RegisterPage": typeof import("./src/./pages/RegisterPage.tsx");
  "pages/PasswordResetPage": typeof import("./src/./pages/PasswordResetPage.tsx");
  "pages/EmailVerificationPage": typeof import("./src/./pages/EmailVerificationPage.tsx");
  "pages/EmailVerificationSuccessPage": typeof import("./src/./pages/EmailVerificationSuccessPage.tsx");
  "layout/rootLayout": typeof import("./src/./layout/rootLayout.tsx");
  "pages/Home": typeof import("./src/./pages/Home.tsx");
  "pages/teach/HomePage": typeof import("./src/./pages/teach/HomePage.tsx");
  "pages/ProfilePage": typeof import("./src/./pages/ProfilePage.tsx");
  "pages/SessionsPage": typeof import("./src/./pages/SessionsPage.tsx");
  "pages/DevicesPage": typeof import("./src/./pages/DevicesPage.tsx");
  "pages/vocabulary/HomePage": typeof import("./src/./pages/vocabulary/HomePage.tsx");
  "layout/socialLayout": typeof import("./src/./layout/socialLayout.tsx");
  "pages/social/HomePage": typeof import("./src/./pages/social/HomePage.tsx");
  "pages/social/MyPostsPage": typeof import("./src/./pages/social/MyPostsPage.tsx");
  "pages/social/RecommendedPage": typeof import("./src/./pages/social/RecommendedPage.tsx");
  "pages/social/NotificationsPage": typeof import("./src/./pages/social/NotificationsPage.tsx");
  "pages/social/FollowingPage": typeof import("./src/./pages/social/FollowingPage.tsx");
  "pages/social/FollowersPage": typeof import("./src/./pages/social/FollowersPage.tsx");
  "pages/social/TrendsPage": typeof import("./src/./pages/social/TrendsPage.tsx");
};